./galRunTest2 ./libgal2DAlphaBlending001.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DAlphaBlending002.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DAlphaBlending003.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DAlphaBlending004.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DAlphaBlending005.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DAlphaBlending006.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DAlphaBlending007.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DAlphaBlendingYUV001.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DAlphablendFilterBlit001.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DAlphablendFilterBlit002.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DAlphablendFilterBlit003.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DAlphablendFilterBlit004.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DAlphablendFilterBlit005.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DAlphablendFilterBlit006.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DAlphablendFilterBlit011.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DAlphablendFilterBlit012.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DAlphablendFilterBlit013.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DAlphablendFilterBlit014.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DAlphablendFilterBlit015.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DAlphablendFilterBlit016.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DAlphablendFilterBlit017.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DAlphablendFilterBlit018.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DAntiFlicker001.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DAntiFlicker002.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DAntiFlicker003.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DBitBlit001.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DBitBlit002.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DBitBlit003.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DBlendFactors_001.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DBlendFactors_002.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DBlendFactors_003.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DBlitFullRotate.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DClear001.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DClear002.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DColorBrush001.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DColorBrush002.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DColorBrush003.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DColorBrush004.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DColorKey.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DColorSource001.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DColorSource002.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DColorSource003.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DColorSource004.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DColorSource005.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DColorSource006.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DColorSource007.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DColorSource008.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DColorSource009.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DDestColorKeyDFBMode.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DDestination001.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DDestination002.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DDestination003.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DDestination004.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DDestination005.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DDestination006.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DDither001.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DDither002.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DFilterBlit001.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DFilterBlit002.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DFilterBlit003.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DFilterBlit004.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DFilterBlit005.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DFilterBlit006.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DFilterBlit007.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DFilterBlit008.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DFilterBlit009.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DFilterBlit010.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DFilterBlit011.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DFilterRotateDither.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DFilterRotateDither002.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DFormatA8_001.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DFormatA8_002.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DFormatA8_003.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DFormatARGB001.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DFormatARGB002.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DFormatTileStatus001.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DFormatTileStatus002.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DFormatTileStatus004.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DFormatTileStatus005.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DFormatTiling001.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DFormatTiling002.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DFormatTiling003.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DFormatTiling004.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DFormatTiling005.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DFormatTiling006.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DFormatYUV001.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DFormatYUV002.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DFormatYUV003.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DFormatYUV004.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DFormatYUV005.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DFormatYUV006.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DFormatYUV007.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DFormatYUV008.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DFormatYUV009.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DFormatYUV010.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DFormatYUV011.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DLine001.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DLine002.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DLine003.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DLine004.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DLine005.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DLine006.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DLine007.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DLine008.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DLine009.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DLine010.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DLine011.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DMaskedBlit.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DMaskedSource.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DMaskedSource001.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DMaskedString.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DMonoBlit001.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DMonoSource.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DMonochromeBrush001.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DMonochromeBrush002.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DMonochromeBrush003.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DMonochromeBrush004.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DMonochromeBrush005.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DMonochromeSource001.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DMonochromeSource002.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DMonochromeSource003.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DMonochromeSource004.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DMonochromeSource005.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DMonochromeSource006.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DMonochromeSource007.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DMultiSourceBlit001.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DMultiSourceBlit002.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DMultiSourceBlit010.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DMultiSourceBlitRotation101.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DMultiSourceBlitRotation102.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DMultiSourceBlitRotation103.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DMultiSourceBlitRotation104.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DMultiSourceBlitRotation105.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DMultiSourceBlitRotation106.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DMultiSourceBlitRotation107.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DMultiSourceBlitRotation201.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DMultiSourceBlitRotation202.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DMultiSourceBlitRotation203.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DMultiSourceBlitRotation204.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DMultiSourceBlitRotation205.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DMultiSourceBlitRotation206.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DMultiSourceBlitRotation207.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DMultiSourceBlitStress.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DMultiply001.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DRotation001.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DRotation002.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DRotation003.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DRotation004.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DRotation005.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DRotation006.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DRotation007.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DRotation008.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DRotation009.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DRotation010.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DRotation011.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DRotation012.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DRotation013.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DRotation014.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DScaleBlit.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DSingleColorBrush001.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DSingleColorBrush002.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DSingleColorBrush003.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DSourceColorKeyDFBMode.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DStress.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DStretchBlit001.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DStretchBlit002.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DStretchBlit003.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DStretchBlit004.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DStretchBlit005.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DStretchBlit006.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DStretchBlit007.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DStretchBlit008.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DStretchBlit009.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DStretchBlit010.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DString.so -c ./galTestCommon.cfg || exit
./galRunTest2 ./libgal2DYUV2RGB.so -c ./galTestCommon.cfg || exit
